const newsActionTypes = {
  FETCH_NEWS_START: 'FETCH_NEWS_START',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAILURE: 'FETCH_NEWS_FAILURE',
  SET_COUNTRY: 'SET_COUNTRY',
  FETCH_NEWS_BY_CATEGORY_START: 'FETCH_NEWS_BY_CATEGORY_START',
  FETCH_NEWS_BY_CATEGORY_SUCCESS: 'FETCH_NEWS_BY_CATEGORY_SUCCESS',
  FETCH_NEWS_BY_CATEGORY_FAILURE: 'FETCH_NEWS_BY_CATEGORY_FAILURE',
  CLEAR_NEWS: 'CLEAR_NEWS',
  CLEAR_NEWS_BY_CATEGORY: 'CLEAR_NEWS_BY_CATEGORY',
}

export default newsActionTypes
